---
name: Run Tests

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Dependencies
        run: pip install selenium==4.9.1 robotframework-seleniumlibrary robotframework
      - name: Run Tests
        run: robot  --outputdir output tests/

